ldvspec/ldvspec/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('ldvspec/', include('lofardata.urls')),
    path('ldvspec/admin/', admin.site.urls, name='admin_app'),
    path('ldvspec/api-auth/', include('rest_framework.urls')),
    path("ldvspec/prometheus/", include("django_prometheus.urls")),
]

ldvspec/lofardata/urls.py
from django.urls import include, path
from django.conf import settings
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view

from .views import api, DataProductView, DataProductDetailsView, InsertMultiDataproductView, GroupCreateUpdateView, \
    ATDBProcessingSiteView, WorkSpecificationCreateUpdateView, WorkSpecificationDetailView, \
    WorkSpecificationDeleteView, WorkSpecificationInputsView, WorkSpecificationATDBTasksView, \
    WorkSpecificationDatasetSizeInfoView, DataProductViewPerSasID, Overview, WorkSpecificationViewset

router = DefaultRouter()
router.register(r'workspecification', WorkSpecificationViewset, basename="workspecification")
router.register(r'processing_site', ATDBProcessingSiteView, basename='processingsite')

urlpatterns = [
    # Authentication
    path('accounts/', include('astronauth.urls')),

    # REST API
    path('api/v1/data/', DataProductView.as_view(), name='dataproduct'),
    path('api/v1/insert_dataproduct/', InsertMultiDataproductView.as_view(), name='dataproduct-insert'),
    path('api/v1/data/<int:pk>/', DataProductDetailsView.as_view(), name='dataproduct-detail-view-api'),

    path('api/v1/uws/', include('uws.urls')),
    path('api/v1/openapi/', get_schema_view(
        title="LDV Specification",
        description="API description",
        version="0.0.1"
    ), name='openapi-schema'),
    path('api/v1/', include(router.urls)),

    # GUI
    path('', Overview.as_view(), name='index'),
    path('api/', api, name='api'),
    path('specification/<int:pk>/', WorkSpecificationDetailView.as_view(), name='specification-detail'),
    path('specification/add/', WorkSpecificationCreateUpdateView.as_view(), name='specification-create'),
    path('specification/update/<int:pk>/', WorkSpecificationCreateUpdateView.as_view(), name='specification-update'),
    path('specification/delete/<int:pk>/', WorkSpecificationDeleteView.as_view(), name='specification-delete'),
    path('specification/inputs/<int:pk>/', WorkSpecificationInputsView.as_view(), name='specification-inputs'),
    path('specification/tasks/<int:pk>/', WorkSpecificationATDBTasksView.as_view(), name='specification-tasks'),
    path('specification/dataset-size-info/<int:pk>/', WorkSpecificationDatasetSizeInfoView.as_view(), name='dataset-size-info'),
    path('specification/dataproducts/<int:pk>', DataProductViewPerSasID.as_view(), name='specification-dataproducts'),
    path('group/add/', GroupCreateUpdateView.as_view(), name='group-create'),
    path('group/update/<int:pk>', GroupCreateUpdateView.as_view(), name='group-update'),
]

if settings.ENABLE_PROFILING:
    urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

ldvspec/lofardata/models.py
import logging

from celery.result import AsyncResult
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.db import IntegrityError, models
from django.utils.translation import gettext_lazy as _
from django_prometheus.models import ExportModelOperationsMixin

from lofardata.templatetags.format import format_size
from lofardata.view_helpers import inputs_processor

logger = logging.getLogger(__name__)


class DataProduct(models.Model):
    obs_id = models.CharField(verbose_name="OBS_ID", max_length=15)
    oid_source = models.CharField(verbose_name="OBS_ID_SOURCE", max_length=15)
    dataproduct_source = models.CharField(max_length=20)
    dataproduct_type = models.CharField(max_length=50)
    project = models.CharField(max_length=50)
    location = models.CharField(max_length=50)
    activity = models.CharField(max_length=50)
    surl = models.CharField(max_length=200, unique=True)
    filesize = models.PositiveBigIntegerField()
    antenna_set = models.CharField(max_length=50, blank=True, null=True, default="")
    instrument_filter = models.CharField(max_length=50, blank=True, null=True, default="")
    dysco_compression = models.BooleanField(blank=True, null=True, default=False)

    @staticmethod
    def insert_dataproduct(
            obs_id,
            oid_source,
            dataproduct_source,
            dataproduct_type,
            project,
            location,
            activity,
            surl,
            filesize,
            antenna_set,
            instrument_filter,
            dysco_compression
    ):

        dp = DataProduct(
            obs_id=obs_id,
            oid_source=oid_source,
            dataproduct_source=dataproduct_source,
            dataproduct_type=dataproduct_type,
            project=project,
            location=location,
            activity=activity,
            filesize=filesize,
            antenna_set=antenna_set,
            instrument_filter=instrument_filter,
            dysco_compression=dysco_compression,
            surl=surl,
        )
        dp.save()
        return dp

    def save(self, *args, **kwargs):
        try:
            super(DataProduct, self).save(*args, **kwargs)
        except IntegrityError:
            logger.warning("Surl '{}' is already present".format(self.surl))
            pass


class DataFilterType(models.TextChoices):
    DROPDOWN = "Dropdown", _("Dropdown")
    FREEFORM = "Free", _("Freeform")

class DataFilterInclusionType(models.TextChoices):
    INCLUDE = "Include", _("Include")
    EXCLUDE = "Exclude", _("Exclude")

class DataFilterCardinalityType(models.TextChoices):
    SINGLE = "Single", _("Single")
    MULTIPLE = "Multiple", _("Multiple")

class DataProductFilter(models.Model):
    field = models.CharField(max_length=100)
    name = models.CharField(max_length=20)
    help_text = models.CharField(max_length=150, blank=True, default="")
    lookup_type = models.CharField(max_length=100)
    filter_type = models.CharField(max_length=20, choices=DataFilterType.choices, default=DataFilterType.FREEFORM)
    filter_inclusion_type = models.CharField(max_length=20, choices=DataFilterInclusionType.choices, default=DataFilterInclusionType.INCLUDE)
    filter_cardinality_type = models.CharField(max_length=20, choices=DataFilterCardinalityType.choices, default=DataFilterCardinalityType.SINGLE)

    def __str__(self):
        return f'({self.pk}) "{self.name}" [{self.field} ->{self.lookup_type}]'


class ATDBProcessingSite(models.Model):
    name = models.CharField(primary_key=True, max_length=100)
    url = models.URLField()
    access_token = models.CharField(max_length=1000, null=True)

    def __str__(self):
        return str(self.name) + " - " + str(self.url)


class SUBMISSION_STATUS(models.TextChoices):
    """Status of Work Specification"""

    # The surls and belonging information are being retrieved
    LOADING = "L", _("loading")
    # Tasks are ready to submit to ATDB
    READY = "R", _("ready")
    # Task are still being submitted to ATDB
    DEFINING = "D", _("defining")
    # Tasks are submitted, check ATDB for current status
    SUBMITTED = "S", _("submitted")
    # Check log, retry submission
    ERROR = "E", _("error")


class PURGE_POLICY(models.TextChoices):
    """ATDB Purge Policy"""

    # @Mancini, what are these?
    YES = "yes", _("yes")
    NO = "no", _("no")
    DO = "do", _("do")  # only purge, no workflow execution


class Group(models.Model):
    """Group to which work specification belongs"""

    name = models.CharField(max_length=50, unique=True)

    # ATDB info
    processing_site = models.ForeignKey(
        ATDBProcessingSite, null=True, blank=True, on_delete=models.SET_NULL
    )
    selected_workflow = models.CharField(max_length=500, null=True)
    selected_workflow_tag = models.CharField(max_length=500, null=True)

    predecessor_specification = models.ForeignKey(
        "lofardata.WorkSpecification",
        null=True,
        on_delete=models.SET_NULL,
        blank=True,
        related_name="+",   # See https://docs.djangoproject.com/en/4.1/ref/models/fields/#django.db.models.ForeignKey.related_name
    )
    filters = models.JSONField(null=True)

    task_filter = models.CharField(max_length=30, blank=True, null=True)

    def ordered_workspecifications(self):
        return self.workspecification_set.order_by('id')


class WorkSpecification(ExportModelOperationsMixin("work-specification"), models.Model):
    """Work Specification"""

    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True)

    group = models.ForeignKey(Group, null=True, blank=True, on_delete=models.CASCADE)

    filters = models.JSONField(null=True)
    # Input data containing sizes/urls for submission to ATDB
    inputs = models.JSONField(null=True, blank=True)

    # ATDB Workflow URL
    selected_workflow = models.CharField(max_length=500, null=True)
    selected_workflow_tag = models.CharField(max_length=500, null=True)

    # Task ID's that were created in ATDB
    atdb_task_ids = ArrayField(models.IntegerField(), null=True, blank=True)
    predecessor_specification = models.ForeignKey(
        "self",
        null=True,
        on_delete=models.SET_NULL,
        related_name="successor",
        blank=True,
    )

    # Should automatically submit the task after defining
    is_auto_submit = models.BooleanField(default=False)

    async_task_result = models.CharField(max_length=100, null=True)
    processing_site = models.ForeignKey(
        ATDBProcessingSite, null=True, on_delete=models.DO_NOTHING
    )
    purge_policy = models.CharField(
        max_length=16, choices=PURGE_POLICY.choices, default=PURGE_POLICY.NO
    )

    task_filter = models.CharField(max_length=30, blank=True, null=True)

    __original_submission_status = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_submission_status = self.submission_status

    def create_successor(self):
        successor = WorkSpecification()
        successor.predecessor_specification = self
        successor.processing_site = self.processing_site
        successor.filters = self.filters

        return successor

    def created_by_display_value(self):
        if self.created_by is None:
            return "Unknown"
        return (
            self.created_by.get_full_name()
            if self.created_by.get_full_name()
            else self.created_by
        )

    def can_be_edited_by(self, user: User) -> bool:
        """
        Indicates whether this specification can be edited (i.e., updated/deleted) by the specified user
        @param user: the user to check access for
        @return: whether the specification can be updated or deleted by the specified user, which is true if:
        - the user is a staff member, OR
        - the specification has not been added to the database yet (in which case, _state == adding) OR
        - the specification was created by the user
        """
        return user.is_staff or self._state.adding or self.created_by_id == user.pk

    @staticmethod
    def can_be_viewed_by(user: User) -> bool:
        """
        Indicates whether this specification can be viewed (i.e., read) by the specified user
        @param user: the user to check access for
        @return: whether the specification can be viewed by the specified user, which is true if:
        - always
        """
        return True

    @staticmethod
    def can_be_submitted_by(user: User) -> bool:
        """
        Indicates whether this specification can be submitted by the specified user
        @param user: the user to check access for
        @return: whether the specification can be submitted by the specified user, which is true if:
        - always
        """
        return True

    @property
    def helpdesk_contact(self):
        # TODO: use API? to already fill in part of the request
        return "https://support.astron.nl/jira/servicedesk/customer/portal/7"

    def is_new(self) -> bool:
        return self.pk is None

    def is_editable(self) -> bool:
        """Indicates whether this specification is editable (i.e., it has not been submitted yet)"""
        return (
            self.submission_status != SUBMISSION_STATUS.SUBMITTED
            and self.submission_status != SUBMISSION_STATUS.DEFINING
            and self.submission_status != SUBMISSION_STATUS.LOADING
        )

    @property
    def get_file_info(self):
        """@return: a tuple of the total_size, number_of_files and average_file_size"""
        total_size, number_of_files, average_file_size = inputs_processor.compute_size_of_inputs(self.inputs)
        return total_size, number_of_files, average_file_size

    @property
    def get_file_info_dict(self):
        total_size, number_of_files, average_file_size = inputs_processor.compute_size_of_inputs(self.inputs)

ldvspec/lofardata/views/api.py
from django.shortcuts import render
from lofardata.models import ATDBProcessingSite

def api(request):
    atdb_hosts = ATDBProcessingSite.objects.values("name", "url")
    return render(request, "lofardata/api.html", {"atdb_hosts": atdb_hosts})

ldvspec/lofardata/templates/lofardata/partial_templates/badges.html
{% load define_action %}
{% if status == "L" %}
    {% define "secondary" as badgecolor %}
    {% define "The work specification is now retrieving the necessary information." as badgeTitle %}
{% elif status == "D" %}
    {% define "secondary" as badgecolor %}
    {% define "The work specification is now being sent to ATDB." as badgeTitle %}
{% elif status == "S" %}
    {% define "green" as badgecolor %}
    {% define "The work specification has been succcesfully processed in ATDB." as badgeTitle %}
{% elif status == "E" %}
    {% define "red" as badgecolor %}
    {% define "Retrieving the files to process or submitting the task to ATDB resulted in an error. Please reports this to the support helpdesk or try again." as badgeTitle %}
{% elif status == "R" %}
    {% if number_of_files == 0 %}
        {% define "orange" as badgecolor %}
        {% define label|add:"*" as label %}
        {% define "The work specification has been created, but does not contain any files. Please inspect the specified filters." as badgeTitle %}
    {% elif number_of_files > 0 %}
        {% define "primary" as badgecolor %}
        {% define "The work specification has been created, but has not yet been sent to ATDB for processing." as badgeTitle %}
    {% endif %}
{% endif %}
<div class="badge badge--{{ badgecolor }} margin-top text text--capitalized"
     data-test-id="submission-status"
     title="{{ badgeTitle }}">
    {{ label }}
</div>

ldvspec/lofardata/templates/lofardata/partial_templates/filter_inputs.html
<div class="custom--div-margin">
    <h3 class="text text--primary text--title">Filters</h3>
    {% for filter in filters %}

    {% if filter.filter_type == 'Free' %}
        <div class="flex-wrapper">
            <div class="flex-wrapper flex-wrapper--row custom__input--fixed-min-width">
                <label class="input__label" for="id_{{ filter.field }}">{{ filter.name }}</label>
                {% if filter.help_text %}
                <a class="tooltip-dias tooltip-dias-right custom--tooltip" data-tooltip="{{ filter.help_text }}">m</a>
                {% endif %}
            </div>
            {% if filter.filter_cardinality_type == 'Single' %}
                <input class="input input--text margin-left margin-bottom" id="id_{{ filter.field }}" name="{{ filter.field }}"
                    data-test-id="{{ filter.name }}" placeholder="Enter {{ filter.name }}" type="text"
                    data-filter="{{ filter.lookup_type }}" value="{{ filter.default }}">
            {% elif filter.filter_cardinality_type == 'Multiple' %}
                <textarea class="input input--text margin-left margin-bottom" id="id_{{ filter.field }}" name="{{ filter.field }}"
                    data-test-id="{{ filter.name }}" placeholder="Enter {{ filter.name }}" type="text"
                      data-filter="{{ filter.lookup_type }}">{{filter.default}}</textarea>
            {% endif %}
        </div>
    {% elif filter.filter_type == 'Dropdown' %}
        <div class="flex-wrapper flex-wrapper--row" id="div_id_filter_{{ filter.name }}">
            <div class="flex-wrapper flex-wrapper--row custom__input--fixed-min-width">
                <label class="input__label" for="id_{{ filter.field }}"
                    data-test-id="{{ filter.name }}">{{filter.name}}</label>
                {% if filter.help_text %}
                <a class="tooltip-dias tooltip-dias-right custom--tooltip" data-tooltip="{{ filter.help_text }}">m</a>
                {% endif %}
            </div>
            <div class="input-select-wrapper icon--inline icon-after icon-after--angle-down margin-left margin-bottom">
                <select class="input input--select custom__input--fixed-width" id="id_{{ filter.field }}"
                    data-test-id="{{ filter.name }}" name="{{ filter.field }}" data-filter="{{ filter.lookup_type }}"
                    style="width: 12rem">
                    {#for some reason, styling is not applied otherwise#}

                    {% if filter.default == "" %}
                    <option selected value="">All</option>
                    {% else %}
                    <option value="">All</option>
                    {% endif%}

                    {% for option in filter.choices %}
                    {% if filter.default == option.0 %}
                    <option selected value="{{ option.0 }}">{{ option.0 }}</option>
                    {% else %}
                    <option value="{{ option.0 }}">{{ option.0 }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
            </div>
        </div>
    {% else %}
        <div class="text text--red">Not supported field</div>
    {% endif %}
    {% endfor %}
</div>

ldvspec/lofardata/templates/lofardata/partial_templates/group_actions.html
{% load define_action %}
{% if group is None %}
    {% define 'Ungrouped' as group_name %}
{% else %}
    {% define group.name as group_name %}
{% endif %}
<input id="collapsible-{{ group_name }}" class="toggle" type="checkbox" {{checked}}>
<label for="collapsible-{{ group_name }}" class="group-toggle">
    {% if group is None %}
        <i>{{ group_name }}</i>
    {% else %}
        {{ group_name }}
    {% endif %}
    <div class="custom--group-actions margin-left">
        {% if group is not None %}
            <a class="button--icon-button margin-left margin-right" href="{% url 'group-update' pk=group.pk %}"
               title="Edit this group" data-test-id="edit-group-{{ group.name }}">
                <span class="icon icon--pen"></span>
            </a>
            <a class="button--icon-button margin-right" href="#"
               data-bind="click: function() { deleteSelectedGroupSpecifications({{group.pk}}); return false }, css: { 'link--disabled': getSelectedGroupedIds({{group.pk}}).length === 0 }"
               title="Delete the selected items">
                <span class="icon icon--color-inherit icon--trash-alt"></span>
            </a>
            <a class="button--icon-button margin-right" href="#"
               data-bind="click: function() { submitSelectedGroupSpecifications({{group.pk}}); return false; }, css: { 'link--disabled': getSelectedGroupedIds({{group.pk}}).length === 0 }"
               title="Submit the selected items">
                <span class="icon icon--color-inherit icon--play"></span>
            </a>
        {% else %}
            <a class="button--icon-button margin-right" href="#"
               data-bind="click: function() { deleteSelectedUngroupedSpecifications(); return false; }, css: { 'link--disabled': selectedUngroupedSpecifications().length === 0 }"
               title="Delete the selected items">
                <span class="icon icon--color-inherit icon--trash-alt"></span>
            </a>
            <a class="button--icon-button margin-right" href="#"
                data-bind="click: function() { submitSelectedUngroupedSpecifications(); return false; }, css: { 'link--disabled': selectedUngroupedSpecifications().length === 0 }"
               title="Submit the selected items">
                <span class="icon icon--color-inherit icon--play"></span>
            </a>
        {% endif %}

    </div>
</label>

ldvspec/lofardata/templates/lofardata/partial_templates/predecessor_field.html
{% load widget_tweaks %}
<div class="flex-wrapper flex-wrapper--row" id="div_id_predecessor">
    <div class="flex-wrapper flex-wrapper--row custom__input--fixed-min-width">
        <label class="input__label"
               for="id_predecessor">{{ form.predecessor_specification.label }}</label>
        <a class="tooltip-dias tooltip-dias-right custom--tooltip"
           data-tooltip="{{ form.predecessor_specification.help_text }}">m</a>
    </div>
    <div class="input-select-wrapper icon--inline icon-after icon-after--angle-down margin-left margin-bottom">
        {% render_field form.predecessor_specification class="input input--select custom__input--fixed-width" %}
    </div>
</div>

ldvspec/lofardata/templates/lofardata/partial_templates/site_workflow_fields.html
<div class="flex-wrapper flex-wrapper--row" id="div_id_processing_site">
    <div class="flex-wrapper flex-wrapper--row custom__input--fixed-min-width">
        <label class="input__label">{{ form.processing_site.label }}*</label>
        <a class="tooltip-dias tooltip-dias-right custom--tooltip"
           data-tooltip="{{ form.processing_site.help_text }}">m</a>
    </div>
    <div class="input-select-wrapper icon--inline icon-after icon-after--angle-down">
        <select class="input input--select custom__input--fixed-width margin-left margin-bottom"
                name="processing_site"
                data-bind="options:processingSites,
                           optionsCaption: '---------',
                           optionsText: function(item) { return item.name + ' - ' + item.url},
                           optionsValue: 'name',
                           value: selectedProcessingSite"
                data-test-id="processing_site"
        ></select>
    </div>
</div>


<div class="flex-wrapper flex-wrapper--row" id="div_id_selected_workflow_tag">
    <div class="flex-wrapper flex-wrapper--row custom__input--fixed-min-width">
        <label class="input__label"
               for="id_selected_workflow_tag">{{ form.selected_workflow_tag.label_tag }}*</label>
        <a class="tooltip-dias tooltip-dias-right custom--tooltip"
           data-tooltip="{{ form.selected_workflow_tag.help_text }}">m</a>
    </div>
    <div class="input-select-wrapper icon--inline icon-after icon-after--angle-down">
        <select class="input input--select custom__input--fixed-width margin-bottom margin-left"
                id="id_selected_workflow_tag"
                data-test-id="workflow_tag"
                name="selected_workflow_tag"
                style="width: 12rem"
                data-bind="options:tags,
                           optionsCaption: caption,
                           value: selectedTag,
                           disable: isLoading">
        </select>
    </div>
</div>


<div class="flex-wrapper flex-wrapper--row" id="div_id_selected_workflow">
    <div class="flex-wrapper flex-wrapper--row custom__input--fixed-min-width">
        <label class="input__label"
               for="id_selected_workflow">{{ form.selected_workflow.label }}*</label>
        <a class="tooltip-dias tooltip-dias-right custom--tooltip"
           data-tooltip="{{ form.selected_workflow.help_text }}">m</a>
    </div>
    <div class="input-select-wrapper icon--inline icon-after icon-after--angle-down">
        <select class="input input--select custom__input--fixed-width margin-bottom margin-left"
                id="id_selected_workflow"
                name="selected_workflow"
                style="width: 12rem"
                data-test-id="workflow"
                data-bind="options:workflowsByTag,
                           optionsCaption: caption,
                           optionsValue: 'workflow_uri',
                           optionsText: 'workflow_uri',
                           value: selectedWorkflow,
                           disable: isLoading">
        </select>
    </div>
</div>

ldvspec/lofardata/templates/lofardata/partial_templates/table_header.html
<div class="table__header" data-test-id="table-header-{{ name }}">
    <div class="table__row table__row--dark table__row--padding">
        <div class="table__cell table__cell--mini">
            <div class="flex-container flex-container--checkboxes">
                <div class="flex-wrapper flex-wrapper--row">
                    <input type="checkbox" id="group-{{ id }}" name="{{ id }}-select-all"
                           class="input custom--checkbox margin-top"
                           onClick="toggle(this,'checkbox-select-{{ id|escapejs }}')">
                </div>
            </div>
        </div>

        <div class="table__cell table__cell--mini">ID
            <a class="tooltip-dias tooltip-dias-bottom"
               data-tooltip="Click on the id to view/edit">m</a>
        </div>

        <div class="table__cell">Creator</div>

        <div class="table__cell">Status
            <a class="tooltip-dias tooltip-dias-bottom"
               data-tooltip="The status w.r.t. ATDB">m</a>
        </div>

        <div class="table__cell">Workflow
            <a class="tooltip-dias tooltip-dias-bottom"
               data-tooltip="The link(s) to the ATDB task details">m</a>
        </div>
        <div class="table__cell">ATDB Tasks
            <a class="tooltip-dias tooltip-dias-bottom"
               data-tooltip="The link(s) to the ATDB task details">m</a>
        </div>
        <div class="table__cell">Data product info
            <a class="tooltip-dias tooltip-dias-bottom"
               data-tooltip="The grouped information about the dataproducts">m</a>
        </div>

        <div class="table__cell">Total Size
            <a class="tooltip-dias tooltip-dias-bottom"
               data-tooltip="The total size">m</a>
        </div>

        <div class="table__cell">Size /task
            <a class="tooltip-dias tooltip-dias-bottom"
               data-tooltip="The average size per task">m</a>
        </div>

        <div class="table__cell">Total files
            <a class="tooltip-dias tooltip-dias-bottom"
               data-tooltip="The number of files per task versus the total number files">m</a>
        </div>

                <div class="table__cell">Files /task
            <a class="tooltip-dias tooltip-dias-bottom"
               data-tooltip="The number of files per task versus the total number files">m</a>
        </div>

        <div class="table__cell">Split
            <a class="tooltip-dias tooltip-dias-bottom"
               data-tooltip="Whether or not the work specification has been splitted in multiple ATDB tasks and if that is recommended or not.">m</a>
        </div>

        <div class="table__cell">Suc
            <a class="tooltip-dias tooltip-dias-bottom"
               data-tooltip="The successors of a work specification (i.e. the children of another work specification)">m</a>
        </div>
        <div class="table__cell">Pre
            <a class="tooltip-dias tooltip-dias-bottom"
               data-tooltip="The predecessor of a work specification (i.e. the parent of a work specification)">m</a>
        </div>

        <div class="table__cell">Actions</div>
    </div>
</div>

ldvspec/lofardata/templates/lofardata/partial_templates/user_guide_link.html
{% load static %}

<a class="" title="User Guide" target="_blank" href="{% static 'documentation/docs/user-guide/'|add:link %}">
    <span class="icon icon--primary icon--user">
        <span class="icon icon--secondary icon--stacked icon--background--main icon--info-circle"></span>
    </span>
</a>