ldvspec/ldvspec/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('ldvspec/', include('lofardata.urls')),
    path('ldvspec/admin/', admin.site.urls, name='admin_app'),
    path('ldvspec/api-auth/', include('rest_framework.urls')),
    path("ldvspec/prometheus/", include("django_prometheus.urls")),
]

ldvspec/lofardata/urls.py
from django.urls import include, path
from django.conf import settings
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view

from .views import api, DataProductView, DataProductDetailsView, InsertMultiDataproductView, GroupCreateUpdateView, \
    ATDBProcessingSiteView, WorkSpecificationCreateUpdateView, WorkSpecificationDetailView, \
    WorkSpecificationDeleteView, WorkSpecificationInputsView, WorkSpecificationATDBTasksView, \
    WorkSpecificationDatasetSizeInfoView, DataProductViewPerSasID, Overview, WorkSpecificationViewset

router = DefaultRouter()
router.register(r'workspecification', WorkSpecificationViewset, basename="workspecification")
router.register(r'processing_site', ATDBProcessingSiteView, basename='processingsite')

urlpatterns = [
    # Authentication
    path('accounts/', include('astronauth.urls')),

    # REST API
    path('api/v1/data/', DataProductView.as_view(), name='dataproduct'),
    path('api/v1/insert_dataproduct/', InsertMultiDataproductView.as_view(), name='dataproduct-insert'),
    path('api/v1/data/<int:pk>/', DataProductDetailsView.as_view(), name='dataproduct-detail-view-api'),

    path('api/v1/uws/', include('uws.urls')),
    path('api/v1/openapi/', get_schema_view(
        title="LDV Specification",
        description="API description",
        version="0.0.1"
    ), name='openapi-schema'),
    path('api/v1/', include(router.urls)),

    # GUI
    path('', Overview.as_view(), name='index'),
    path('api/', api, name='api'),
    path('specification/<int:pk>/', WorkSpecificationDetailView.as_view(), name='specification-detail'),
    path('specification/add/', WorkSpecificationCreateUpdateView.as_view(), name='specification-create'),
    path('specification/update/<int:pk>/', WorkSpecificationCreateUpdateView.as_view(), name='specification-update'),
    path('specification/delete/<int:pk>/', WorkSpecificationDeleteView.as_view(), name='specification-delete'),
    path('specification/inputs/<int:pk>/', WorkSpecificationInputsView.as_view(), name='specification-inputs'),
    path('specification/tasks/<int:pk>/', WorkSpecificationATDBTasksView.as_view(), name='specification-tasks'),
    path('specification/dataset-size-info/<int:pk>/', WorkSpecificationDatasetSizeInfoView.as_view(), name='dataset-size-info'),
    path('specification/dataproducts/<int:pk>', DataProductViewPerSasID.as_view(), name='specification-dataproducts'),
    path('group/add/', GroupCreateUpdateView.as_view(), name='group-create'),
    path('group/update/<int:pk>', GroupCreateUpdateView.as_view(), name='group-update'),
]

if settings.ENABLE_PROFILING:
    urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

ldvspec/lofardata/models.py
import logging

from celery.result import AsyncResult
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.db import IntegrityError, models
from django.utils.translation import gettext_lazy as _
from django_prometheus.models import ExportModelOperationsMixin

from lofardata.templatetags.format import format_size
from lofardata.view_helpers import inputs_processor

logger = logging.getLogger(__name__)


class DataProduct(models.Model):
    obs_id = models.CharField(verbose_name="OBS_ID", max_length=15)
    oid_source = models.CharField(verbose_name="OBS_ID_SOURCE", max_length=15)
    dataproduct_source = models.CharField(max_length=20)
    dataproduct_type = models.CharField(max_length=50)
    project = models.CharField(max_length=50)
    location = models.CharField(max_length=50)
    activity = models.CharField(max_length=50)
    surl = models.CharField(max_length=200, unique=True)
    filesize = models.PositiveBigIntegerField()
    antenna_set = models.CharField(max_length=50, blank=True, null=True, default="")
    instrument_filter = models.CharField(max_length=50, blank=True, null=True, default="")
    dysco_compression = models.BooleanField(blank=True, null=True, default=False)

    @staticmethod
    def insert_dataproduct(
            obs_id,
            oid_source,
            dataproduct_source,
            dataproduct_type,
            project,
            location,
            activity,
            surl,
            filesize,
            antenna_set,
            instrument_filter,
            dysco_compression
    ):

        dp = DataProduct(
            obs_id=obs_id,
            oid_source=oid_source,
            dataproduct_source=dataproduct_source,
            dataproduct_type=dataproduct_type,
            project=project,
            location=location,
            activity=activity,
            filesize=filesize,
            antenna_set=antenna_set,
            instrument_filter=instrument_filter,
            dysco_compression=dysco_compression,
            surl=surl,
        )
        dp.save()
        return dp

    def save(self, *args, **kwargs):
        try:
            super(DataProduct, self).save(*args, **kwargs)
        except IntegrityError:
            logger.warning("Surl '{}' is already present".format(self.surl))
            pass


class DataFilterType(models.TextChoices):
    DROPDOWN = "Dropdown", _("Dropdown")
    FREEFORM = "Free", _("Freeform")

class DataFilterInclusionType(models.TextChoices):
    INCLUDE = "Include", _("Include")
    EXCLUDE = "Exclude", _("Exclude")

class DataFilterCardinalityType(models.TextChoices):
    SINGLE = "Single", _("Single")
    MULTIPLE = "Multiple", _("Multiple")

class DataProductFilter(models.Model):
    field = models.CharField(max_length=100)
    name = models.CharField(max_length=20)
    help_text = models.CharField(max_length=150, blank=True, default="")
    lookup_type = models.CharField(max_length=100)
    filter_type = models.CharField(max_length=20, choices=DataFilterType.choices, default=DataFilterType.FREEFORM)
    filter_inclusion_type = models.CharField(max_length=20, choices=DataFilterInclusionType.choices, default=DataFilterInclusionType.INCLUDE)
    filter_cardinality_type = models.CharField(max_length=20, choices=DataFilterCardinalityType.choices, default=DataFilterCardinalityType.SINGLE)

    def __str__(self):
        return f'({self.pk}) "{self.name}" [{self.field} ->{self.lookup_type}]'


class ATDBProcessingSite(models.Model):
    name = models.CharField(primary_key=True, max_length=100)
    url = models.URLField()
    access_token = models.CharField(max_length=1000, null=True)

    def __str__(self):
        return str(self.name) + " - " + str(self.url)


class SUBMISSION_STATUS(models.TextChoices):
    """Status of Work Specification"""

    # The surls and belonging information are being retrieved
    LOADING = "L", _("loading")
    # Tasks are ready to submit to ATDB
    READY = "R", _("ready")
    # Task are still being submitted to ATDB
    DEFINING = "D", _("defining")
    # Tasks are submitted, check ATDB for current status
    SUBMITTED = "S", _("submitted")
    # Check log, retry submission
    ERROR = "E", _("error")


class PURGE_POLICY(models.TextChoices):
    """ATDB Purge Policy"""

    # @Mancini, what are these?
    YES = "yes", _("yes")
    NO = "no", _("no")
    DO = "do", _("do")  # only purge, no workflow execution


class Group(models.Model):
    """Group to which work specification belongs"""

    name = models.CharField(max_length=50, unique=True)

    # ATDB info
    processing_site = models.ForeignKey(
        ATDBProcessingSite, null=True, blank=True, on_delete=models.SET_NULL
    )
    selected_workflow = models.CharField(max_length=500, null=True)
    selected_workflow_tag = models.CharField(max_length=500, null=True)

    predecessor_specification = models.ForeignKey(
        "lofardata.WorkSpecification",
        null=True,
        on_delete=models.SET_NULL,
        blank=True,
        related_name="+",   # See https://docs.djangoproject.com/en/4.1/ref/models/fields/#django.db.models.ForeignKey.related_name
    )
    filters = models.JSONField(null=True)

    task_filter = models.CharField(max_length=30, blank=True, null=True)

    def ordered_workspecifications(self):
        return self.workspecification_set.order_by('id')


class WorkSpecification(ExportModelOperationsMixin("work-specification"), models.Model):
    """Work Specification"""

    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True)

    group = models.ForeignKey(Group, null=True, blank=True, on_delete=models.CASCADE)

    filters = models.JSONField(null=True)
    # Input data containing sizes/urls for submission to ATDB
    inputs = models.JSONField(null=True, blank=True)

    # ATDB Workflow URL
    selected_workflow = models.CharField(max_length=500, null=True)
    selected_workflow_tag = models.CharField(max_length=500, null=True)

    # Task ID's that were created in ATDB
    atdb_task_ids = ArrayField(models.IntegerField(), null=True, blank=True)
    predecessor_specification = models.ForeignKey(
        "self",
        null=True,
        on_delete=models.SET_NULL,
        related_name="successor",
        blank=True,
    )

    # Should automatically submit the task after defining
    is_auto_submit = models.BooleanField(default=False)

    async_task_result = models.CharField(max_length=100, null=True)
    processing_site = models.ForeignKey(
        ATDBProcessingSite, null=True, on_delete=models.DO_NOTHING
    )
    purge_policy = models.CharField(
        max_length=16, choices=PURGE_POLICY.choices, default=PURGE_POLICY.NO
    )

    task_filter = models.CharField(max_length=30, blank=True, null=True)

    __original_submission_status = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_submission_status = self.submission_status

    def create_successor(self):
        successor = WorkSpecification()
        successor.predecessor_specification = self
        successor.processing_site = self.processing_site
        successor.filters = self.filters

        return successor

    def created_by_display_value(self):
        if self.created_by is None:
            return "Unknown"
        return (
            self.created_by.get_full_name()
            if self.created_by.get_full_name()
            else self.created_by
        )

    def can_be_edited_by(self, user: User) -> bool:
        """
        Indicates whether this specification can be edited (i.e., updated/deleted) by the specified user
        @param user: the user to check access for
        @return: whether the specification can be updated or deleted by the specified user, which is true if:
        - the user is a staff member, OR
        - the specification has not been added to the database yet (in which case, _state == adding) OR
        - the specification was created by the user
        """
        return user.is_staff or self._state.adding or self.created_by_id == user.pk

    @staticmethod
    def can_be_viewed_by(user: User) -> bool:
        """
        Indicates whether this specification can be viewed (i.e., read) by the specified user
        @param user: the user to check access for
        @return: whether the specification can be viewed by the specified user, which is true if:
        - always
        """
        return True

    @staticmethod
    def can_be_submitted_by(user: User) -> bool:
        """
        Indicates whether this specification can be submitted by the specified user
        @param user: the user to check access for
        @return: whether the specification can be submitted by the specified user, which is true if:
        - always
        """
        return True

    @property
    def helpdesk_contact(self):
        # TODO: use API? to already fill in part of the request
        return "https://support.astron.nl/jira/servicedesk/customer/portal/7"

    def is_new(self) -> bool:
        return self.pk is None

    def is_editable(self) -> bool:
        """Indicates whether this specification is editable (i.e., it has not been submitted yet)"""
        return (
            self.submission_status != SUBMISSION_STATUS.SUBMITTED
            and self.submission_status != SUBMISSION_STATUS.DEFINING
            and self.submission_status != SUBMISSION_STATUS.LOADING
        )

    @property
    def get_file_info(self):
        """@return: a tuple of the total_size, number_of_files and average_file_size"""
        total_size, number_of_files, average_file_size = inputs_processor.compute_size_of_inputs(self.inputs)
        return total_size, number_of_files, average_file_size

    @property
    def get_file_info_dict(self):
        total_size, number_of_files, average_file_size = inputs_processor.compute_size_of_inputs(self.inputs)

ldvspec/lofardata/views/api.py
from django.shortcuts import render
from lofardata.models import ATDBProcessingSite

def api(request):
    atdb_hosts = ATDBProcessingSite.objects.values("name", "url")
    return render(request, "lofardata/api.html", {"atdb_hosts": atdb_hosts})

ldvspec/lofardata/templates/lofardata/workspecification/create_update.html
{% extends 'lofardata/index.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load define_action %}
{% load widget_tweaks %}
{% load json %}

{% block myBlock %}
    <div class="overlay">
        <div class="modal-dias-wrapper">
            <div class="modal-dias modal-dias--fit-content">
                <a class="icon icon--times button--close" href="{% url 'index' %}"></a>
                <header class="flex-wrapper flex-wrapper--centered flex-wrapper--column">
                    {% if object.pk %}
                        <h2 class="title text">Edit Work Specification {{ object.pk }}
                            {% include 'lofardata/partial_templates/user_guide_link.html' with link="work-specification/editing" %}
                        </h2>
                        <form method="post" action="{% url 'specification-update' object.pk %}">
                    {% else %}
                        <h2 class="title text text">New Work Specification
                            {% include 'lofardata/partial_templates/user_guide_link.html' with link="work-specification/creating" %}
                        </h2>
                        <form method="post" action="{% url 'specification-create' %}">
                    {% endif %}

                    {% csrf_token %}
                    <div class="flex-wrapper flex-wrapper--row flex-wrapper--start">
                        <!-- Standard input fields -->
                        <div class="custom--div-margin">
                            <h3 class="text text--primary text--title">Selection</h3>
                            <div class="flex-wrapper flex-wrapper--row" id="div_id_group">
                                <div class="flex-wrapper flex-wrapper--row custom__input--fixed-min-width">
                                    <label class="input__label">{{ form.group.label }}</label>
                                    <a class="tooltip-dias tooltip-dias-right custom--tooltip"
                                       data-tooltip="{{ form.group.help_text }}">m</a>
                                </div>
                                <div class="input-select-wrapper icon--inline icon-after icon-after--angle-down">
                                    <select class="input input--select custom__input--fixed-width margin-left margin-bottom"
                                            name="group"
                                            data-bind="options:groups,
                                                       optionsCaption: '---------',
                                                       optionsText: function(item) { return item.name },
                                                       optionsValue: 'id',
                                                       value: selectedGroup"
                                            data-test-id="group">
                                    </select>
                                </div>
                            </div>

                            <!-- Site and workflow inputs -->
                            {% include 'lofardata/partial_templates/site_workflow_fields.html' %}

                            <!-- Predecessor Field-->
                            {% include 'lofardata/partial_templates/predecessor_field.html' %}

                            <div class="flex-wrapper flex-wrapper--row" id="div_id_batch_size">
                                <div class="flex-wrapper flex-wrapper--row custom__input--fixed-min-width">
                                    <label class="input__label"
                                           for="id_batch_size">{{ form.batch_size.label_tag }}</label>
                                    <a class="tooltip-dias tooltip-dias-right custom--tooltip"
                                       data-tooltip="{{ form.batch_size.help_text }}">m</a>
                                </div>
                                {% render_field form.batch_size class="input input--select custom__input--fixed-width margin-left margin-bottom" type="number" data-test-id='batch-size-input' %}
                            </div>

                            <div class="flex-wrapper flex-wrapper--row" id="div_id_task_filter">
                                <div class="flex-wrapper flex-wrapper--row custom__input--fixed-min-width">
                                    <label class="input__label"
                                           for="id_task_filter">{{ form.task_filter.label_tag }}</label>
                                    <a class="tooltip-dias tooltip-dias-right custom--tooltip"
                                       data-tooltip="{{ form.task_filter.help_text }}">m</a>
                                </div>
                                {% render_field form.task_filter class="input input--select custom__input--fixed-width margin-left margin-bottom" data-bind="value: taskFilter" data-test-id='task-filter-input' %}
                            </div>

                            <div class="flex-wrapper flex-wrapper--row" id="div_id_auto_submit">
                                {% render_field form.is_auto_submit class="input custom--checkbox margin-top" type="checkbox" data-test-id='auto-submit-checkbox' %}
                                <label class="input__label">{{ form.is_auto_submit.label }}</label>
                                <a class="tooltip-dias tooltip-dias-right custom--tooltip"
                                   data-tooltip="{{ form.is_auto_submit.help_text }}">m</a>
                            </div>
                        </div>

                        <!-- Filter fields -->
                        {% include 'lofardata/partial_templates/filter_inputs.html' %}

                    </div>

                    <div class="flex-wrapper flex-wrapper--centered margin-bottom margin-top">
                        <button class="button button--primary margin-right"
                                type="submit"
                                name="action"
                                value="Create"
                                data-test-id="create-update"
                                title="
                                {% if object.pk %}
                                Update the task
                                {% else %}
                                Create the task to inspect the result. Send it later to ATDB.
                                {% endif %}">

                            {% if object.pk %}
                                Update
                            {% else %}
                                Create
                            {% endif %}
                        </button>
                        <button class="button button--primary margin-right" type="submit"
                                value="Successor"
                                name="action"
                                title="Submit the task and add a successor task.">Add successor
                        </button>
                        <a class="button button--red button--primary margin-left" href="{% url 'index' %}">Cancel</a>
                    </div>

                    </form>
                </header>
                {% if form.errors %}
                    <div class="popup-bar popup-bar--red">
                        <span class="icon icon--left icon--color-inherit icon--times"></span>
                        <div class="flex-wrapper flex-wrapper--column">
                            The input is invalid:
                            {% for field, errors in form.errors.items %}
                                {% for error in errors %}
                                    {% if field == '__all__' %}
                                        <li class="text text--red text--faded">{{ error }}</li>
                                    {% else %}
                                        <li class="text text--red text--faded">{{ field }}: {{ error }}</li>
                                    {% endif %}
                                {% endfor %}
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/knockout/3.5.0/knockout-min.js'></script>
    <script type="text/javascript">
        const processingSite = "{% url 'processingsite-detail' 'replace' %}";
        const existingWorkflow = '{{ object.selected_workflow|default_if_none:"" }}';
        const existingWorkflowTag = '{{ object.selected_workflow_tag|default_if_none:"" }}';
        const processingSites = {{ processing_sites | json }};
        const initialProcessingSite = '{{ object.processing_site.name|default:single_processing_site }}';
        const groups = {{ groups | json }};
        const existingGroup = '{{ object.group.id|default_if_none:"null" }}';
        const existingTaskFilter = '{{ object.task_filter|default_if_none:"" }}';
        const pk = {{ object.pk|default_if_none:0 }};
    </script>
    <script src="{% static 'update_workflow.js' %}"></script>
{% endblock %}

ldvspec/lofardata/templates/lofardata/workspecification/dataproducts.html
{% extends 'lofardata/index.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load define_action %}
{% load widget_tweaks %}
{% load format %}

{% block myBlock %}
    <div class="overlay">
        <div class="modal-dias-wrapper">
            <div class="modal-dias modal-dias--fit-content custom--modal-size">
                <a class="icon icon--times button--close"  href="{{request.META.HTTP_REFERER}}"></a>
                {% if dataproduct_info %}
                    <header class="flex-wrapper flex-wrapper--centered flex-wrapper--column">
                        <h2 class="title">Dataproduct information of SAS ID {{ sas_id }}
                            <a class="tooltip-dias tooltip-dias-bottom"
                               data-tooltip="The general data product information for this work specification based on the retrieved information from the SAS ID">m</a>
                        </h2>
                    </header>
                    <div class="table margin-bottom">
                        <div class="table__header">
                            <div class="table__row table__row--dark table__row--padding">
                                <div class="table__cell">Property</div>
                                <div class="table__cell">Value</div>
                            </div>
                        </div>
                        <div class="table__content">
                            {% for key, value in dataproduct_info.items %}
                                {% if value|length > 0 %}
                                    <div class="table__row table__row--dark table__row--padding">
                                        <div class="table__cell table__cell--title">{{ key }}</div>
                                        <div class="table__cell">
                                            {% for item in value %}
                                                {% if key == 'dysco_compression' %}
                                                    {% format_to_percentage item %}
                                                {% else %}
                                                    {{ item }}
                                                {% endif %}
                                                {% if not forloop.last %}&{% endif %}
                                            {% endfor %}
                                        </div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                {% else %}
                    <div class="flex-wrapper flex-wrapper--centered flex-wrapper--column">
                        <p class="text--red">The information is not present.</p>
                        <p>This information is directly linked to given SAS ID which is incorrect. </p>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

ldvspec/lofardata/templates/lofardata/workspecification/dataset_size_info.html
{% extends 'lofardata/index.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load define_action %}
{% load widget_tweaks %}
{% load format %}

{% block myBlock %}
    <div class="overlay">
        <div class="modal-dias-wrapper">
            <div class="modal-dias modal-dias--fit-content custom--modal-size">
                <a class="icon icon--times button--close" href="{{ request.META.HTTP_REFERER }}"></a>
                <header class="flex-wrapper flex-wrapper--centered flex-wrapper--column">
                    <h2 class="title">Size distributions for work specification {{ object.pk }}
                        <a class="tooltip-dias tooltip-dias-bottom"
                           data-tooltip="The size distribution of the input files of this work specification">m</a>
                    </h2>
                </header>
                <div class="flex-wrapper flex-wrapper--row">
                    <div class="custom--chart-styling" id="chartdiv"></div>
                    <div class="table table--unbordered margin-top custom-size-table">
                        <div class="table__content">
                            <div class="table__row table__row--dark table__row--padding">
                                <div class="table__cell table__cell--title">Total files</div>
                                <div class="table__cell table__cell--horizontal-center">{{ object.get_file_info.1 }}</div>
                            </div>
                            <div class="table__row table__row--dark table__row--padding">
                                <div class="table__cell table__cell--title">Minimum</div>
                                <div class="table__cell table__cell--horizontal-center">{{ min_size }}</div>
                            </div>
                            <div class="table__row table__row--dark table__row--padding">
                                <div class="table__cell table__cell--title">Maximum</div>
                                <div class="table__cell table__cell--horizontal-center">{{ max_size }}</div>
                            </div>
                            <div class="table__row table__row--dark table__row--padding">
                                <div class="table__cell table__cell--title">Total</div>
                                <div class="table__cell table__cell--horizontal-center"> {% format_size object.get_file_info.0 %}</div>
                            </div>
                            <div class="table__row table__row--dark table__row--padding">
                                <div class="table__cell table__cell--title">Average</div>
                                <div class="table__cell table__cell--horizontal-center"> {% format_size object.get_file_info.2 %}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Amcharts -->

    <!-- Data retriever -->
    <script>
        const y_max = {{ biggest_bucket }};
        const xaxis_key = "file_size";
        const xaxis_header = "File size";
        const yaxis_key = "total_number_files";
        const yaxis_header = "Number of files";
        const xaxis_values = {{ bins|safe }};
        const yaxis_values = {{ counts|safe }};

        <!-- Construct the data the way AMCharts needs it -->
        let data = [];
        for (let i = 0; i < {{ n_bins }}; i++) {
            let entry = {}
            entry[xaxis_key] = xaxis_values[i] === xaxis_values[i + 1] ? xaxis_values[i] : xaxis_values[i] + " - " + xaxis_values[i + 1]
            entry[yaxis_key] = yaxis_values[i]
            data[i] = entry
        }
    </script>
    <!-- Resources -->
    <script src="https://cdn.amcharts.com/lib/5/index.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/xy.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/themes/Animated.js"></script>
    <!-- Script code -->
    <script src="{% static 'histogram_amcharts.js' %}"></script>

{% endblock %}

ldvspec/lofardata/templates/lofardata/workspecification/delete.html
{% extends 'lofardata/index.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load define_action %}
{% load widget_tweaks %}

{% block myBlock %}
    <div class="overlay">
        <div class="modal-dias-wrapper">
            <div class="modal-dias modal-dias--fit-content">
                <a class="icon icon--times button--close" href="{% url 'index' %}"></a>
                    <header class="flex-wrapper flex-wrapper--centered flex-wrapper--column">
                        <h2 class="title">Delete Work Specification {{ object.pk }}?</h2>
                        <p class="text text--semi-bold">Deleting a work specification cannot be undone. </p>
                        <p>If the task has been sent to ATDB, it will not be
                            deleted there.</p>
                    </header>
                    <div class="flex-wrapper flex-wrapper--centered margin-bottom margin-top">
                        <form method="post" action="{% url 'specification-delete' object.pk %}">
                            {% csrf_token %}
                            <button class="button button--primary button--red margin-right" type="submit"
                                    value="Confirm">
                                Delete
                            </button>
                        </form>
                        <a class="button button--secondary margin-left"
                           href="{% url 'index' %}">Cancel</a>
                    </div>
            </div>
        </div>
    </div>
{% endblock %}